name: go-backend-test

networks:
  backend_test:
    name: go-backend-test

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    expose:
      - 8000
    networks:
      - backend_test
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
      - POSTGRES_PORT
    depends_on:
      - db_test
    volumes:
      - ./:/app

  db_test:
    image: postgres:latest
    expose:
      - 5432
    restart: on-failure
    networks:
      - backend
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
