version: "3.7"

networks:
  backend:
    name: go-backend

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - backend
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
      - POSTGRES_PORT
    depends_on:
      - db
    volumes:
      - ./:/app

    command: ["./wait-for-it.sh", "db:5432", "--", "air"]

  db:
    image: postgres:latest
    ports:
      - 7432:5432
    expose:
      - 5432
    restart: on-failure
    networks:
      - backend
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
