version: "3.7"

networks:
  backend:
    name: go-backend

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - backend
    env_file:
      - env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 7432:5432
    expose:
      - 5432
    restart: on-failure
    networks:
      - backend
    env_file:
      - .env
